# Generated by Django 5.2.6 on 2025-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight')], max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('weekly_goal', models.CharField(choices=[('lose_0.5', 'Lose 0.5kg per week'), ('lose_1', 'Lose 1kg per week'), ('maintain', 'Maintain weight'), ('gain_0.5', 'Gain 0.5kg per week'), ('gain_1', 'Gain 1kg per week')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
