# Generated by Django 5.2.6 on 2025-09-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('high_protein', 'High Protein'), ('low_carb', 'Low Carb'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free')], max_length=50)),
                ('is_healthy', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('food_item', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_diet.userprofile')),
            ],
            options={
                'unique_together': {('user', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MealSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swapped_food', models.CharField(max_length=200)),
                ('swapped_calories', models.IntegerField()),
                ('swap_reason', models.CharField(choices=[('preference', 'Personal Preference'), ('dietary', 'Dietary Restriction'), ('variety', 'Want Variety'), ('availability', 'Food Availability')], default='preference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_meals', to='fitness_diet.mealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_diet.userprofile')),
            ],
        ),
    ]
