# Generated by Django 5.2.6 on 2025-09-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_diet", "0002_fooddatabase_mealplan_mealswap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalorieCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("height", models.FloatField()),
                ("actual_weight", models.FloatField()),
                ("dream_weight", models.FloatField()),
                ("total_daily_calorie_need", models.FloatField()),
                ("calories_burned", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness_diet.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preference", models.CharField(max_length=50)),
                ("required_calories", models.IntegerField()),
                ("breakfast", models.TextField()),
                ("lunch", models.TextField()),
                ("dinner", models.TextField()),
                ("snacks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness_diet.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="food_images/"),
                ),
                ("recognized_food", models.CharField(max_length=200)),
                ("calories", models.IntegerField()),
                ("protein", models.FloatField(blank=True, null=True)),
                ("carbs", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness_diet.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("heart_disease", "Heart Disease"),
                            ("lung_disease", "Lung Disease"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("probability", models.FloatField()),
                ("recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness_diet.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_weight", models.FloatField()),
                ("duration_weeks", models.IntegerField()),
                ("weight_change_kg", models.FloatField()),
                ("physical_activity_level", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness_diet.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("calories_burned", models.IntegerField()),
                ("workout_plan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness_diet.userprofile",
                    ),
                ),
            ],
        ),
    ]
