# Generated by Django 5.2.6 on 2025-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_diet", "0003_caloriecalculation_dietplan_foodrecognition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
